### ISSUE TITLE
Update to latest rand_core version

### ISSUE THREAD

**Issue by SirWindfield** [eldruin/wyhash-rs#3]
Using `rand_core@0.5` fails to compile since the versions differ.

**Comment by eldruin** [comment]
I have released [version 0.4.1](https://crates.io/crates/wyhash/0.4.1) upgrading `rand_core` to 0.5 (0.4.0 contained a small formatting mistake).
I had to increase the minor version because the minimum supported Rust version has changed from 1.31.0 to 1.32.0.
I believe this should be solved now. Please feel free to reopen otherwise.
